### ISSUE TITLE
Role enum

### ISSUE THREAD

**Issue by VladOsipov** [Fargus811/Competition#12]
Why do you need main method inside the enum?
The same question is about sayHello method

**Comment by Fargus811** [comment]
Andrew showed me how can I use it for

**Comment by VladOsipov** [comment]
I think it was just for local testing. You should remove such code from your commits

**Comment by VladOsipov** [comment]
@Fargus811 good job! Main method has been removed. What about sayHello method?

**Comment by Fargus811** [comment]
Done.
