### ISSUE TITLE
class IInMemoryCoachRepository

### ISSUE THREAD

**Issue by trair18** [Fargus811/Competition#2]
change name of field(try to use Shift+F6)

**Comment by trair18** [comment]
`@Override
    public Coach findById(int id) {
        Coach fake = new Coach();
        fake.setId(id);
        int index = coachList.indexOf(fake);
        return sportsmanList.get(index);
    }`

understand why this code doesn't work in current version

**Comment by Fargus811** [comment]
Have done

**Comment by trair18** [comment]
change fields and methods order(fields should be first) and also intervals, ctrl + L

**Comment by Fargus811** [comment]
I will try

**Comment by VladOsipov** [comment]
Closed as a duplicate of https://github.com/Fargus811/Competition/issues/14#issue-530270014
