### ISSUE TITLE
task with *

### ISSUE THREAD

**Issue by trair18** [Fargus811/Competition#3]
`@Override
    public Coach findById(int id) {
        Coach fake = new Coach();
        fake.setId(id);
        int index = coachList.indexOf(fake);
        return sportsmanList.get(index);
    }`

understand why this code doesn't work in current version

_Originally posted by @trair18 in https://github.com/Fargus811/Competition/issues/2#issuecomment-555160399_

**Comment by Fargus811** [comment]
потому что return sporstsmanList , а надо CoachList

**Comment by trair18** [comment]
method `indexOf`use `equals()` for search object in list. You didn't implement it, so they didn't work. Now it should be right.
(Boyz, correct me if i wrong)
