### ISSUE TITLE
class IInMemoryCoachRepository

### ISSUE THREAD

**Issue by trair18** [Fargus811/Competition#4]
`Override
    public List<Sportsman> findByWeight(int weight) {
        List<Sportsman> weightSportsman = new ArrayList<>();
        for (Sportsman sportsman : sportsmanList
        ) {
            if (sportsman.getWeight() == weight) {
                weightSportsman.add(sportsman);
            }
        }
        return weightSportsman;
    }`

You should return Coachs!

**Comment by Fargus811** [comment]
have done
