### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by VladOsipov** [Fargus811/Competition#8]
Name of package userInterface looks not good.
According to java naming convention packages shouldn't be named  in camel case. It would be better to use name as ui or split this package to 2 packages.

Also please take a look at coachcommands and sportsmancommands.
First of all packages should be named in singular form.
Moreover, it would be better to create package "command" and then create packages "coach", "sportsman", etc. inside

**Comment by Fargus811** [comment]
Ok, I will change them

**Comment by VladOsipov** [comment]
Reviewed. “ui” package is done. Please, change others according to the comment

**Comment by Fargus811** [comment]
Done.
